### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by RogueMaster** [derskythe/flipperzero-shapshup#9]
As of the latest set of changes, your app needs to be refactored to compile on dev branch.

**Comment by derskythe** [comment]
@RogueMaster what you mean by refactoring?

**Comment by RogueMaster** [comment]
Have you tried compiling against OFW dev? You might need these changes: https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/ac02ded49aaea7e97363b19ff282c537daf0f648 but other changes too...

**Comment by derskythe** [comment]
You mean this #7
This is issue is dublicate

**Comment by RogueMaster** [comment]
> You mean this one #7
> Current issue is duplicate

Not at all
